version: "3.7"
services:
  api:
    build:
      args:
        user: iamthebookingengine
        uid: 1000
      context: ./api/
      dockerfile: Dockerfile
    image: bookingengine-api
    container_name: bookingengine-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${API_PATH}:/var/www
    networks:
      - bookingengine
  db:
    image: mysql:8.0
    container_name: bookingengine-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - bookingengine
  nginx:
    image: nginx:1.17-alpine
    container_name: bookingengine-nginx
    restart: unless-stopped
    ports:
      - ${API_PORT}:80
    volumes:
      - ${API_PATH}:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - bookingengine

networks:
  bookingengine:
    driver: bridge